source 'https://rubygems.org'

gemspec
gem 'recap'

group :development do
  gem 'capistrano', '2.15.5'
  gem 'rake', '~> 13.0'
  gem 'bump'
  gem 'newrelic_rpm'
end

group :test do
  gem 'rspec'
  gem 'capistrano-spec'
end
